### PR TITLE
MXE: Workaround a bug in autoconf >= 2.70

### PR DESCRIPTION
**Pull request by orgads**
https://savannah.gnu.org/support/?110503

### CODE REVIEW

**Comment by orgads** [comment]
I don't like this change that much. Maybe patching autogen.sh or the configuration files will be better. My autoconf-foo is low :)

**Comment by lephilousophe** [comment]
OK, so if I understand correctly, it's not needed by dockerized-bb because we don't have autotools 2.70 in Debian stable.
Could you try he following change instead?
```
cd '$(SOURCE_DIR)' && NOCONFIGURE=true GTKDOCIZE=false ./autogen.sh
```
The bug report seems to say that it should work and it avoids messing with filesystem.

**Comment by orgads** [comment]
Ok, that worked. Thanks!

**Comment by lephilousophe** [comment]
Great!

**Pull request merged**
