### PR TITLE
MXE: Update to GCC 11

### PR DESCRIPTION
**Pull request by orgads**
This depends on some of the other PRs. And I suppose you won't like it anyway. Pushing for reference :)

### CODE REVIEW

**Comment by lotharsm** [comment]
I think pushing it to GCC 11 is a good idea. The GCC version I use for the release builds is slightly older, so I think it's good to have the buildbot running on a "future" version in order to be able to spot any issues caused by newer GCC versions _before_ we run into trouble with the releases.

+1 from me.

**Comment by lephilousophe** [comment]
If I am not mistaken, MXE provides GCC 5.5.0 which is quite... oldish.
I am not confident at all by switch to master branch of MXE as there are many bugs.
The latest tag, which we use, has GCC10 in plugins. Why not switch on this for now?
I already considered this before but as I have no Windows to test I preferred to stick on standard GCC.

**Comment by orgads** [comment]
gcc 10 is ok too.

I tested on Windows and it worked for me.

**Comment by orgads** [comment]
Ok, I pushed gcc10 as #40 and based this commit on top of it. I'll change the title to WIP so it doesn't get submitted.

**Comment by orgads** [comment]
mxe was tagged just now. Updated this commit.

**Comment by lephilousophe** [comment]
Wow wow wow. Too much changes on MXE side!
I will some tests this week-end and merge this one if everything works with latest tag.

**Comment by orgads** [comment]
Ok, I'll squash it to avoid 2 commits. I'll leave both PRs open for now.

**Comment by lephilousophe** [comment]
I merged this manually because there was some issues with MXE upgrade.
Thanks!

**Pull request closed without merging**
