### PR TITLE
TOOLCHAINS: Fix references to obsolete python package

### PR DESCRIPTION
**Pull request by orgads**
Get prepared for Debian 12 :)

### CODE REVIEW

**Comment by lotharsm** [comment]
Just to make sure, the `python-is-python3` command makes sure that `python` always invokes `python3`? What's the difference between the "usual" `python3` package?

**Comment by orgads** [comment]
Yes. `python3` doesn't install a binary/symlink `python`, so you can only execute it as `python3`, and if you execute `python` you get a "command not found" error.

**Comment by lephilousophe** [comment]
It's way too soon. There are still packages which require python2 (for example ps3py).
No need to hurry, Bullseye isn't even 6 months old.
Plus, I don't see the point of adding python-is-python3 when python3 package is enough.

**Comment by orgads** [comment]
Like I said, `python3` doesn't provide `python`, so if a script has a shebang of `#!/usr/bin/env python` it won't run.

If you still need python2, that's a valid argument.

**Pull request closed without merging**
